version: '3.8'

services:
  fastapi_test_app:
    container_name: fastapi_test_app
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - '8000:8000'
    depends_on:
      postgres_test_db:
        condition: service_healthy

  postgres_test_db:
    container_name: postgres_test_db
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: "${TEST_DB_USER}"
      POSTGRES_PASSWORD: "${TEST_DB_PASS}"
      POSTGRES_DB: "test_db"
      PGUSER: "${TEST_DB_PGUSER}"
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${TEST_DB_PGUSER}", "pg_isready", "-U", "${TEST_DB_USER}", "-d", "test_db"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis_test:
    container_name: redis_test
    image: redis:alpine

volumes:
  postgres_data:
